config/routes.rb
Rails.application.routes.draw do
  resources :control_panels
  resources :clients
  devise_for :users
  get 'pages/index'
  get 'pages/portfolio'
  get 'pages/about'
  resources :pics
  get 'pages/control'

  root 'pages#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/control_panel.rb
class ControlPanel < ActiveRecord::Base
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:firstname, :lastname, :description, :email, :phone)
    end
end

app/controllers/control_panels_controller.rb
class ControlPanelsController < ApplicationController
  before_action :set_control_panel, only: [:show, :edit, :update, :destroy]
  before_action :require_admin,

  # GET /control_panels
  # GET /control_panels.json
  def index
    @control_panels = ControlPanel.all
  end

  # GET /control_panels/1
  # GET /control_panels/1.json
  def show
  end

  # GET /control_panels/new
  def new
    @control_panel = ControlPanel.new
  end

  # GET /control_panels/1/edit
  def edit
  end

  # POST /control_panels
  # POST /control_panels.json
  def create
    @control_panel = ControlPanel.new(control_panel_params)

    respond_to do |format|
      if @control_panel.save
        format.html { redirect_to @control_panel, notice: 'Control panel was successfully created.' }
        format.json { render :show, status: :created, location: @control_panel }
      else
        format.html { render :new }
        format.json { render json: @control_panel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /control_panels/1
  # PATCH/PUT /control_panels/1.json
  def update
    respond_to do |format|
      if @control_panel.update(control_panel_params)
        format.html { redirect_to @control_panel, notice: 'Control panel was successfully updated.' }
        format.json { render :show, status: :ok, location: @control_panel }
      else
        format.html { render :edit }
        format.json { render json: @control_panel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /control_panels/1
  # DELETE /control_panels/1.json
  def destroy
    @control_panel.destroy
    respond_to do |format|
      format.html { redirect_to control_panels_url, notice: 'Control panel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_control_panel
      @control_panel = ControlPanel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def control_panel_params
      params.require(:control_panel).permit(:index, :update, :show, :destroy)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def portfolio
  end

  def blog
  end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  helper_method :current_user, :user_signed_in?

  def index
    @pics = Pic.all.order('created_at DESC')
  end

  def new
    @pic = current_user.pics.build
  end

  def show

  end

  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      flash[:success] = "The picture was posted properly"
      redirect_to pic_path(@pic)
    else
      redirect_to :new
    end
  end

  def edit
  end

  def update
    if @pic.update(pic_params)
      flash[:success] = "Picture updated successfully"
      redirect_to @pic
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy

    redirect_to pics_path
  end

  private

  def pic_params
    params.require(:pic).permit(:title, :description, :image)
  end

    @pic = Pic.find(params[:id])
  end

  def require_user
    if !user_signed_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

  def require_same_user
    if current_user != @pic.user
      flash[:danger] = "You can only do this action if you are the author"
      redirect_to root_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/control_panels_helper.rb
module ControlPanelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :description %>
    <%= f.input :email %>
    <%= f.input :phone %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/_sidebar.html.erb
<div id="wrapper">
  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="#menu-toggle" id="menu-toggle"><%= controller_name.upcase %></a>
      </li>
      <li class="nav-divider"></li>
      <li>
        <%= link_to "#{action_name.upcase}", clients_path %>
      </li>
      <li>
        <%= link_to 'NEW CLIENT', new_client_path %>
      </li>
      <li>
        <%= link_to "LOG OUT", destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </div>
</div>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<%= render 'layouts/sidebar' %>

<div id="row">
  <div class="col-md-8 col-md-offset-3" >
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3>CLIENT CONTROL PANEL</h3>
      </div>
      <div class="panel-body">
        <div class="btn-group pull-right">
          <%= link_to "NEW CLIENT", new_client_path, class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    </div>

    <% @clients.each do |client| %>
        <div class="panel panel-info">
          <div class="box panel-heading panel-default">
            <%= client.firstname.upcase %> <%= client.lastname.upcase %>
          </div>
          <div class="panel-body">
            <%= client.description %>
          </div>
          <div class="panel-footer">
            <div class="row">
              <div class="col-md-12 col-offset-2">
                <%= client.email %>, <%= client.phone %>
                <div class="btn-group pull-right">
                  <% if user_signed_in? %>
                      <%= link_to 'EDIT', edit_client_path(client), class:"btn btn-primary btn-md" %>
                      <%= link_to 'DELETE', client, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary btn-md" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
    <% end %>
    </div>

  </div>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @client.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @client.lastname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @client.description %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/control_panels/_form.html.erb
<%= simple_form_for(@control_panel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :index %>
    <%= f.input :update %>
    <%= f.input :show %>
    <%= f.input :destroy %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/control_panels/edit.html.erb
<h1>Editing Control Panel</h1>

<%= render 'form' %>

<%= link_to 'Show', @control_panel %> |
<%= link_to 'Back', control_panels_path %>

app/views/control_panels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Control Panels</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th>Update</th>
      <th>Show</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @control_panels.each do |control_panel| %>
      <tr>
        <td><%= control_panel.index %></td>
        <td><%= control_panel.update %></td>
        <td><%= control_panel.show %></td>
        <td><%= control_panel.destroy %></td>
        <td><%= link_to 'Show', control_panel %></td>
        <td><%= link_to 'Edit', edit_control_panel_path(control_panel) %></td>
        <td><%= link_to 'Destroy', control_panel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Control panel', new_control_panel_path %>

app/views/control_panels/new.html.erb
<h1>New Control Panel</h1>

<%= render 'form' %>

<%= link_to 'Back', control_panels_path %>

app/views/control_panels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @control_panel.index %>
</p>

<p>
  <strong>Update:</strong>
  <%= @control_panel.update %>
</p>

<p>
  <strong>Show:</strong>
  <%= @control_panel.show %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @control_panel.destroy %>
</p>

<%= link_to 'Edit', edit_control_panel_path(@control_panel) %> |
<%= link_to 'Back', control_panels_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright &copy; <a href="www.mgarsteck.com">Full Site</a>

  </small>

</footer>

app/views/layouts/_messages.html.erb
<div class="row center">

  <div class="col-xs-12 col-xs-offset-0">
    <% flash.each do |name, msg| %>

        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "mGarsteck", pages_control_path, class: "navbar-brand", id: "logo"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "PORTFOLIO", pics_path %></li>
        <li><%= link_to "ABOUT", pages_about_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ACCOUNT <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "MY PROFILE", root_path %></li>
                <li><%= link_to "ADD PHOTOS", new_pic_path %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "MASTER CONTROL", pages_control_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "LOGIN", user_session_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_pic.html.erb
<div class="row" align="center">
  <div class="box panel panel-default">
    <%= link_to image_tag pic.image.url(:medium) %>
    <h4><%= link_to pic.title, pic %></h4>
    <p>by: <%= pic.user.email.upcase %></p>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div id="wrapper">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <h3><%= controller_name.upcase %></h3>
      </li>
      <li class="nav-divider"></li>
      <li>
        <%= link_to 'DASHBOARD', pages_control_path %>
      </li>
      <li>
        <%= link_to 'CLIENTS', clients_path %>
      </li>
      <li>
        <%= link_to 'SETTINGS', edit_user_registration_path %>
      </li>
      <li>
        <a href="#">IMAGES</a>
      </li>
      <li>
        <a href="#">BLOG</a>
      </li>
      <li>
        <%= link_to "LOG OUT", destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </div>
</div>

<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Menu Toggle Script -->
<script>
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mgarsteck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/footer' %>
  <%= render 'layouts/messages' %>


  <%= yield %>


</body>
</html>

app/views/pages/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="#"><h4><%= controller_name.upcase %></h4></a>
    </li>
    <li class="nav-divider"></li>
    <li>
      <%= link_to 'EDIT PROFILE', edit_user_registration_path %>
    </li>
    <li>
      <a href="#">MANAGE PHOTOS</a>
    </li>
    <li>
      <a href="#">ANALYTICS</a>
    </li>
    <li>
      <%= link_to "CLIENTS", clients_path %>
    </li>
    <li>
      <%= link_to "LOG OUT", destroy_user_session_path, method: :delete %>
    </li>
  </ul>
</div>

app/views/pages/control.html.erb
<div id="wrapper">

  <!-- Sidebar -->
  <%= render 'layouts/sidebar' %>

  <!-- Page Content -->
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><span class="glyphicon glyphicon-th-list"></span></a>

        <div class="col-lg-12">
          <div class="page-header">
            <h1 class="center">Main Controller Page: </h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /#wrapper -->

app/views/pages/index.html.erb
<%= render 'layouts/navbar' %>
<div class="row">
  <div class="col-md-12">
    <div class="page-header center">
      <h3>HOME PAGE</h3>
    </div>
    <div class="control-label col-sm-offset-2 col-sm-8">


        <% if user_signed_in? %>
          <div class="panel panel-info">
            <div class="panel-heading">Signed in as</div>
            <div class="panel-body">
              <h3><%= current_user.email %></h3>
            </div>

            <div class="panel-heading">User ID</div>
            <div class="panel-body">
              <h3><%= current_user.id %></h3>
            </div>
          </div>

            <% if current_user.pics.length == 0 %>
              <div class="well well-lg">

                <h2>You have no pictures</h2>
                <%= link_to "Upload New Picture", new_pic_path, class: 'btn btn-primary btn-lg' %>
              </div>
            <% else %>
              <div class="panel panel-info">

                <div class="panel-heading">Number of Pictures</div>
                <div class="panel-body">
                  <h3><%= current_user.pics.length %></h3>
                </div>
              </div>


<!-- Display all of your pics -->
              <% current_user.pics.each do |pic| %>
                  <div class="row" align="center">
                    <div class="well well-lg">
                      <h2><%= link_to pic.title, pic %></h2>
                      <%= image_tag pic.image.url(:medium) %>
                      <ul class = "edit-delete">
                        <li><%= link_to "Edit", edit_pic_path(pic), class: 'button' %></li>
                        <li><%= link_to "Destroy", pic_path(pic), class: 'button', method: :delete, data: {confirm: "Are you sure?"} %></li>
                      </ul>

                    </div>
                  </div>
              <% end %>
            <% end %>

        <% else %>
          <h1>Not Signed In</h1>

        <% end %>

    </div>
  </div>
</div>

app/views/pages/portfolio.html.erb
<h1>Portfolio Page</h1>
<h3>pages#portfolio</h3>

app/views/pics/_form.html.erb
<%= render "shared/errors", obj: @pic %>

<div class="row">
  <div class="col-md-8 col-md-offset-1" >
    <%= simple_form_for @pic, html: {multipart: true} do |f| %>
        <div class = 'form-group'>
          <div class="control-label col-sm-offset-2 col-sm-8">
            <%= f.input :image, input_html: {class: 'form-control'} %>
          </div>
        </div>
        <div class = 'form-group'>
          <div class="control-label col-sm-offset-2 col-sm-8">
            <%= f.input :title, input_html: {class: 'form-control'} %>
          </div>
        </div>
        <div class = 'form-group'>
          <div class="control-label col-sm-offset-2 col-sm-8">
            <%= f.input :description, input_html: {class: 'form-control'} %>
          </div>
        </div>
        <div class="col-sm-offset-2 col-sm-12">
          <%= f.button :submit, class: "btn btn-primary" %> <%= link_to "Cancel", pics_path, class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>

app/views/pics/edit.html.erb
<div class="row">
  <div class="col-md-12">

    <div class="page-header center">
      <h1><h1>Edit </h1><%= @pic.title %></h1>
    </div>
    <div class="control-label col-sm-offset-2 col-sm-8">

      <%= image_tag @pic.image.url(:medium) %>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/pics/index.html.erb
<%= render 'layouts/sidebar' %>

<div class="col-md-6 col-md-offset-3">
  <div class="page-header center">
    <h3>PORTFOLIO</h3>
  </div>
  <div id="pics" class="transitions-enabled">
    <%= render partial: 'layouts/pic', collection: @pics %>
  </div>
</div>

app/views/pics/new.html.erb
<%= render 'layouts/sidebar' %>
<%= render 'form' %>

app/views/pics/show.html.erb
<%= render 'layouts/sidebar' %>

<div id="pic_show">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="center panel panel-heading pic_image">
          <%= image_tag @pic.image.url(:medium)%>
        </div>

        <div class="panel-body center">
          <h3><%= @pic.title.upcase %></h3>
          <p> <%= @pic.description %></p>
        </div>

        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6">
              <p>by: <%= @pic.user.email.upcase %></p>
            </div>
            <div class="btn-group pull-right">
              <% if current_user == @pic.user %>
                  <%= link_to "Edit", edit_pic_path, class: 'btn btn-primary btn-lg' %>
                  <%= link_to "Destroy", pic_path, class: 'btn btn-primary btn-lg', method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row center">
      <div class="col-xs-12 col-offest-8">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              PREVENTED THIS ACTION FROM BEING SUCCESSFUL:
            </h2>
            <div class="panel-body center">
              <ul style="list-style-type:none">
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>